In [1]:
!pip install xlrd
!pip install lxml

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting xlrd
  Obtaining dependency information for xlrd from https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl.metadata
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 2.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: lxml in /home/arberaga/anaconda3/lib/python3.11/site-packages (4.9.3)

In [2]:
# import os
# import pandas as pd
# red = pd.read_html(r'/home/arberaga/Downloads/Taipei/0G3XyuSY.xls', encoding="utf-8")[0]
# blue = pd.read_html(r'/home/arberaga/Downloads/Taipei/1BuCXNLO.xls', encoding="utf-8")[0]
# print(list(red.columns))
# print(list(blue.columns))

In [3]:
# red.columns = red.columns.droplevel()
# red.columns

In [4]:
# import os
# import pandas as pd

# cwd = os.path.abspath('/home/arberaga/Downloads/New_Taipei_City') #If i leave it empty and have files in /Viktor it works but I have the desired excel files in /excel 

# files = os.listdir(cwd)  
# #print(files)


# newtaipeidf = pd.DataFrame()
# for file in files:
#    if file.endswith('.xls'):
#        red = pd.read_html('/home/arberaga/Downloads/New_Taipei_City/' + file, encoding="utf-8")[0]
#        red.columns = red.columns.droplevel()
#        newtaipeidf = newtaipeidf.append(red, ignore_index=True)

In [5]:
# newtaipeidf.to_excel(r'/home/arberaga/Downloads/New_Taipei_City/merged.xlsx')

In [100]:
from sklearn.preprocessing import OrdinalEncoder

In [5]:
import os
import pandas as pd

newtaipeidf = pd.read_excel(r'/home/arberaga/Downloads/New_Taipei_City/merged.xlsx')
taipeidf = pd.read_excel(r'/home/arberaga/Downloads/Taipei/merged.xlsx')
taoyuandf = pd.read_excel(r'/home/arberaga/Downloads/Taoyuan/merged.xlsx')
taichungdf = pd.read_excel(r'/home/arberaga/Downloads/Taichung/merged.xlsx')

In [6]:
newtaipeidf_split = newtaipeidf.drop(axis=1,labels=["Unnamed: 18_level_1","Unnamed: 19_level_1","Unnamed: 0","車位總價(萬元)"])
newtaipeidf_split["City"] = "New Taipei"
taipeidf_split = taipeidf.drop(axis=1,labels=["Unnamed: 18_level_1","Unnamed: 19_level_1","Unnamed: 0","車位總價(萬元)"])
taipeidf_split["City"] = "Taipei"
taoyuandf_split = taoyuandf.drop(axis=1,labels=["Unnamed: 18_level_1","Unnamed: 19_level_1","Unnamed: 0","車位總價(萬元)"])
taoyuandf_split["City"] = "Taoyuan"
taichungdf_split = taichungdf.drop(axis=1,labels=["Unnamed: 18_level_1","Unnamed: 19_level_1","Unnamed: 0","車位總價(萬元)"])
taichungdf_split["City"] = "Taichung"

#removed the column parking space as it contains only 2 values in 350K rows

In [9]:
all_df_split = pd.concat([newtaipeidf_split,taipeidf_split,taoyuandf_split,taichungdf_split])
all_df_split.sort_values("交易日期",inplace=True)	
all_df_split.rename(inplace=True,columns={"地段位置或門牌":"Lot location or house number","社區簡稱":"Community abbreviation","交易日期":"transaction date","總價(萬元)":"Total price (10,000 yuan)","單價(萬元/坪)":"Unit price (10,000 yuan/square meter)","總面積(坪)":"Total area(ping)","主建物佔比":"Proportion of main building","型態":"type","屋齡":"House age","樓別/樓高":"Floor type/floor height","交易標的":"Transaction object","交易筆棟數":"Number of transactions","建物現況格局":"The current layout of the building","管理組織":"management organization","電梯":"elevator","主要用途":"The main purpose","備註":"Remark"})
# DONT drop rows which have the column Proportion of main building & The current layout of the building as NaN,
# all_df_split.dropna(subset=['Proportion of main building','The current layout of the building'],inplace=True)
all_df_split.reset_index(inplace=True)
all_df_split.drop(labels=["index","Transaction object"],axis=1,inplace=True)
all_df_split[all_df_split["Total price (10,000 yuan)"].isna()]
all_df_split

,Lot location or house number,Community abbreviation,transaction date,"Total price (10,000 yuan)","Unit price (10,000 yuan/square meter)",Total area(ping),Proportion of main building,type,House age,Floor type/floor height,Number of transactions,The current layout of the building,management organization,elevator,The main purpose,Remark,City
0,土城區中華路一段５７號四樓,NaN,104/07/01,820.0,32.2,25.50,100.00%,公寓(5樓含以下無電梯),39.0,"四層,陽台/四層",土:1 建:1車:0,3房2廳2衛,無,NaN,住家用,含增建或未登記建物。含增建或未登記建物。;,New Taipei
1,平鎮區湧?路２５巷１５號,NaN,104/07/01,218.0,0.0,9.60,NaN,透天厝,45.0,全/一層,土:2 建:1車:0,2房1廳1衛,無,NaN,住家用,NaN,Taoyuan
2,平鎮區金陵路２５８號２F,NaN,104/07/01,521.3,17.2,30.38,74.63%,華廈(10層含以下有電梯),22.0,二層/七層,土:2 建:1車:0,3房2廳2衛,有,NaN,住家用,NaN,Taoyuan
3,平鎮區平東路３０２巷４號,NaN,104/07/01,310.0,0.0,25.05,NaN,透天厝,36.0,全/二層,土:1 建:1車:0,4房3廳2衛,無,NaN,住家用,含增建或未登記建物。含增建或未登記建物。;,Taoyuan
4,平鎮區高雙路４８巷２８號,馥園,104/07/01,1100.0,0.0,61.34,NaN,透天厝,9.0,全/四層,土:1 建:1車:0,4房3廳3衛,有,NaN,住家用,NaN,Taoyuan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385743,三芝區田心子１５之１１號四樓,NaN,110/07/29,155.0,5.4,28.76,77.46%,公寓(5樓含以下無電梯),26.0,四層/五層,土:2 建:1車:0,3房2廳2衛,有,無,住家用,陽台外推;,New Taipei
385744,八里區龍米路一段２４６號十四樓之１,麗池海岸,110/07/29,480.0,23.9,20.10,69.96%,住宅大樓(11層含以上有電梯),20.0,十四層/二十一層,土:1 建:1車:0,1房1廳1衛,有,有,住家用,親友、員工、共有人或其他特殊關係間之交易;,New Taipei
385745,三芝區淺水灣街７之１號八樓,佛朗明哥B區,110/07/29,580.0,16.3,35.69,33.14%,華廈(10層含以下有電梯),24.0,八層/十層,土:1 建:1車:0,2房2廳1衛,有,有,住家用,其他增建:露台夾層;其他增建;,New Taipei
385746,三芝區田心子１５之９號三樓,NaN,110/07/30,168.0,6.8,24.57,76.45%,公寓(5樓含以下無電梯),26.0,三層/五層,土:2 建:1車:0,3房2廳1衛,無,無,住家用,窗框增建。其他增建;,New Taipei
385747,八里區文昌一街８號九樓,陽光峇里,110/07/31,570.0,24.8,22.99,60.02%,住宅大樓(11層含以上有電梯),3.0,九層/十四層,土:1 建:1車:0,2房1廳1衛,有,有,住家用,NaN,New Taipei

In [43]:
trainmask = (all_df_split['transaction date'] < "110/01/01")
#validatemask = (all_df_split['transaction date'] >= "110/01/01") & (all_df_split['transaction date'] <= "110/03/31")
testmask = (all_df_split['transaction date'] >= "110/01/01")
train_df = all_df_split.loc[trainmask]
test_df = all_df_split.loc[testmask]
#validate_df = all_df_split.loc[validatemask]
#duplicates will not be removed

In [92]:
all_df_split["Proportion of main building"] = all_df_split["Proportion of main building"].fillna(train_df["Proportion of main building"])

In [93]:
all_df_split["House age"] = all_df_split["House age"].fillna(train_df["House age"].median())

In [94]:
all_df_split["The main purpose"] = all_df_split["The main purpose"].fillna("住家用")

In [95]:
all_df_split["The current layout of the building"] = all_df_split["The current layout of the building"].fillna("3房2廳2衛")

In [96]:
all_df_split["Number of transactions"] = all_df_split["Number of transactions"].fillna("土:1 建:1車:0")

In [97]:
all_df_split["Floor type/floor height"] = all_df_split["Floor type/floor height"].fillna("全/四層")

In [80]:
all_df_split.head(1).to_string()

'  Lot location or house number Community abbreviation transaction date  Total price (10,000 yuan)  Unit price (10,000 yuan/square meter)  Total area(ping) Proportion of main building          type  House age Floor type/floor height Number of transactions The current layout of the building management organization elevator The main purpose                 Remark        City  geometry_lat  geometry_lng Land Construction Car\n0                土城區中華路一段５７號四樓                    NaN        104/07/01                      820.0                                   32.2              25.5                     100.00%  公寓(5樓含以下無電梯)       39.0                四層,陽台/四層             土:1 建:1車:0                             3房2廳2衛                       無      NaN              住家用  含增建或未登記建物。含增建或未登記建物。;  New Taipei     24.988061    121.445661    1            1   0'

In [91]:
print(all_df_split[all_df_split["The current layout of the building"].isna()])

Empty DataFrame
Columns: [Lot location or house number, Community abbreviation, transaction date, Total price (10,000 yuan), Unit price (10,000 yuan/square meter), Total area(ping), Proportion of main building, type, House age, Floor type/floor height, Number of transactions, The current layout of the building, management organization, elevator, The main purpose, Remark, City, geometry_lat, geometry_lng, Land, Construction, Car]
Index: []

[0 rows x 22 columns]

In [98]:
#split "number of transactions" column into 3 different columns based on semicolon of column
# x = "土:1 建:1車:0"
# arr = re.findall("(\d)",x)
import re

def handle(x,chars):

    val = re.findall(chars+":(\d*)",x)
    if val == []:
        val = [0]
    return val[0]

def handle2(x,chars):

    val = re.findall("(\d*)"+chars,x)
    if val == []:
        val = [0]
    return val[0]


all_df_split["Land"] = all_df_split["Number of transactions"].apply(lambda x : handle(x, "土"))
all_df_split["Construction"] = all_df_split["Number of transactions"].apply(lambda x : handle(x, "建"))
all_df_split["Car"] = all_df_split["Number of transactions"].apply(lambda x : handle(x, "車"))

all_df_split["Bedrooms"] = all_df_split["The current layout of the building"].apply(lambda x : handle2(x, "房"))
all_df_split["Living rooms"] = all_df_split["The current layout of the building"].apply(lambda x : handle2(x, "廳"))
all_df_split["Bathrooms"] = all_df_split["The current layout of the building"].apply(lambda x : handle2(x, "衛"))
all_df_split["elevator"].fillna("無")
all_df_split["elevator"].replace({"無":0,"有":1},inplace=True)
all_df_split["management organization"].fillna("無")
all_df_split["management organization"].replace({"無":0,"有":1},inplace=True)
all_df_split["management organization"].describe()

count    385748.000000
mean          0.474507
std           0.499350
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: management organization, dtype: float64

In [103]:
#Creating external nodes and edges
ordinal_enc = OrdinalEncoder()

all_df_split['Encoded_type'] = ordinal_enc.fit_transform(all_df_split[['type']]).astype(int)
Encoded_type = all_df_split[["type", "Encoded_type"]].drop_duplicates().sort_values(by='Encoded_type')

all_df_split['Encoded_floor'] = ordinal_enc.fit_transform(all_df_split[['Floor type/floor height']]).astype(int)
Encoded_floor = all_df_split[["Floor type/floor height", "Encoded_floor"]].drop_duplicates().sort_values(by='Encoded_floor')

all_df_split['Encoded_purpose'] = ordinal_enc.fit_transform(all_df_split[['The main purpose']]).astype(int)
Encoded_purpose = all_df_split[["The main purpose", "Encoded_purpose"]].drop_duplicates().sort_values(by='Encoded_purpose').reset_index().drop(columns="index")


Encoded_floor = Encoded_floor.dropna(subset=["Floor type/floor height"]).reset_index().drop(columns="index")
Encoded_purpose = Encoded_purpose.dropna(subset=["The main purpose"]).reset_index().drop(columns="index")
Encoded_type.to_csv('nodes_type_data.csv')
Encoded_floor.to_csv('nodes_floor_data.csv')
Encoded_purpose.to_csv('nodes_purpose_data.csv')


type_data = all_df_split["Encoded_type"].copy()
floor_data = all_df_split["Encoded_floor"].copy()
purpose_data = all_df_split["Encoded_purpose"].copy()


type_data = type_data.reset_index().rename(columns={"index":"node_id"})
floor_data = floor_data.reset_index().rename(columns={"index":"node_id"})
purpose_data = purpose_data.reset_index().rename(columns={"index":"node_id"})
print(len(purpose_data))
type_data = type_data[type_data["Encoded_type"]>=0]
floor_data = floor_data[floor_data["Encoded_floor"]>=0]
purpose_data = purpose_data[purpose_data["Encoded_purpose"]>=0]

print(len(purpose_data))

type_data.to_csv('edges_type_data.csv')
floor_data.to_csv('edges_floor_data.csv')
purpose_data.to_csv('edges_purpose_data.csv')

all_df_split['Encoded_city'] = ordinal_enc.fit_transform(all_df_split[['City']]).astype(int)
Encoded_city = all_df_split[["City", "Encoded_city"]].drop_duplicates().sort_values(by='Encoded_city').reset_index().drop(columns="index")
Encoded_city.to_csv('nodes_city_data.csv')
city_data = all_df_split["Encoded_city"].copy()
city_data = city_data.reset_index().rename(columns={"index":"node_id"})
city_data = city_data[city_data["Encoded_city"]>=0]

city_data.to_csv('edges_city_data.csv')

all_df_split_removed =all_df_split.drop(columns=["Community abbreviation","type","Floor type/floor height","The main purpose", "Number of transactions", "The current layout of the building", "Remark"])

/tmp/ipykernel_822/1169165428.py:4: RuntimeWarning: invalid value encountered in cast
  all_df_split['Encoded_type'] = ordinal_enc.fit_transform(all_df_split[['type']]).astype(int)

385748
385748

In [105]:
all_df_split_removed["geometry_lat"] = all_df_split_removed["geometry_lat"].fillna(all_df_split_removed["geometry_lat"].median())
all_df_split_removed["geometry_lng"] = all_df_split_removed["geometry_lng"].fillna(all_df_split_removed["geometry_lng"].median())

In [ ]:
import requests
import pandas as pd


for row in range(0,1):
    reqStr = "https://maps.googleapis.com/maps/api/geocode/json?address={}&key=AIzaSyAuB9gxQtRiLw42XoTiDwgGFtIkVR3-8ls&language=zh-CN".format("平鎮區高雙路４８巷２８號")
    x = requests.get(reqStr).json()
    res = pd.DataFrame.from_dict(x['results'])
    print(res)

                                  address_components      formatted_address  \
0  [{'long_name': '28 号', 'short_name': '28 号', '...  324台湾桃園市平鎮區高雙路48號28 号

                                            geometry  partial_match  \
0  {'location': {'lat': 24.9567763, 'lng': 121.19...           True

                                            place_id         types
0  EkkyOCDlj7csIE5vLiA0OCwgR2Fvc2h1YW5nIFJkLCBQaW...  [subpremise]

In [106]:
missingdata = all_df_split_removed[all_df_split_removed["geometry_lat"].isna()]
missingdata

Empty DataFrame
Columns: [Lot location or house number, transaction date, Total price (10,000 yuan), Unit price (10,000 yuan/square meter), Total area(ping), Proportion of main building, House age, management organization, elevator, City, geometry_lat, geometry_lng, Land, Construction, Car, Bedrooms, Living rooms, Bathrooms, Encoded_type, Encoded_floor, Encoded_purpose, Encoded_city]
Index: []

[0 rows x 22 columns]

In [ ]:
# for i, row in all_df_split.iterrows():
#     if i < 317858: continue # skip first x rows
#     #print(i)
#     reqStr = "https://maps.googleapis.com/maps/api/geocode/json?address={}&key=AIzaSyAuB9gxQtRiLw42XoTiDwgGFtIkVR3-8ls&language=zh-CN".format(row["Lot location or house number"])
#     x = requests.get(reqStr).json()
#     res = pd.DataFrame.from_dict(x['results'])
#     if(len(res))<1:
#         print("missing",i)
#         continue
#     all_df_split.loc[i, "geometry_lat"] = res.loc[0].get("geometry")["location"]["lat"]
#     all_df_split.loc[i, "geometry_lng"] = res.loc[0].get("geometry")["location"]["lng"]

In [109]:
all_df_split

,Lot location or house number,Community abbreviation,transaction date,"Total price (10,000 yuan)","Unit price (10,000 yuan/square meter)",Total area(ping),Proportion of main building,type,House age,Floor type/floor height,...,Land,Construction,Car,Bedrooms,Living rooms,Bathrooms,Encoded_type,Encoded_floor,Encoded_purpose,Encoded_city
0,土城區中華路一段５７號四樓,NaN,104/07/01,820.0,32.2,25.50,100.00%,公寓(5樓含以下無電梯),39.0,"四層,陽台/四層",...,1,1,0,3,2,2,2,2349,2,0
1,平鎮區湧?路２５巷１５號,NaN,104/07/01,218.0,0.0,9.60,NaN,透天厝,45.0,全/一層,...,2,1,0,2,1,1,11,1654,2,3
2,平鎮區金陵路２５８號２F,NaN,104/07/01,521.3,17.2,30.38,74.63%,華廈(10層含以下有電梯),22.0,二層/七層,...,2,1,0,3,2,2,8,1491,2,3
3,平鎮區平東路３０２巷４號,NaN,104/07/01,310.0,0.0,25.05,NaN,透天厝,36.0,全/二層,...,1,1,0,4,3,2,11,1659,2,3
4,平鎮區高雙路４８巷２８號,馥園,104/07/01,1100.0,0.0,61.34,NaN,透天厝,9.0,全/四層,...,1,1,0,4,3,3,11,1669,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385743,三芝區田心子１５之１１號四樓,NaN,110/07/29,155.0,5.4,28.76,77.46%,公寓(5樓含以下無電梯),26.0,四層/五層,...,2,1,0,3,2,2,2,2395,2,0
385744,八里區龍米路一段２４６號十四樓之１,麗池海岸,110/07/29,480.0,23.9,20.10,69.96%,住宅大樓(11層含以上有電梯),20.0,十四層/二十一層,...,1,1,0,1,1,1,0,2179,2,0
385745,三芝區淺水灣街７之１號八樓,佛朗明哥B區,110/07/29,580.0,16.3,35.69,33.14%,華廈(10層含以下有電梯),24.0,八層/十層,...,1,1,0,2,2,1,8,1742,2,0
385746,三芝區田心子１５之９號三樓,NaN,110/07/30,168.0,6.8,24.57,76.45%,公寓(5樓含以下無電梯),26.0,三層/五層,...,2,1,0,3,2,1,2,1107,2,0
385747,八里區文昌一街８號九樓,陽光峇里,110/07/31,570.0,24.8,22.99,60.02%,住宅大樓(11層含以上有電梯),3.0,九層/十四層,...,1,1,0,2,1,1,0,1187,2,0

In [110]:
all_df_split_removed.to_csv("Taiwan_all_rows_with_locationv5.csv")

In [111]:
#all_df_split_removed = all_df_split_removed.drop(columns=["Unnamed: 0"])
all_df_split_removed['Encoded_city'] = ordinal_enc.fit_transform(all_df_split_removed[['City']]).astype(int)
Encoded_city = all_df_split_removed[["City", "Encoded_city"]].drop_duplicates().sort_values(by='Encoded_city').reset_index().drop(columns="index")
Encoded_city.to_csv('nodes_city_data.csv')
city_data = all_df_split_removed["Encoded_city"].copy()
city_data = city_data.reset_index().rename(columns={"index":"node_id"})
city_data.to_csv('edges_city_data.csv')
all_df_split_removed

,Lot location or house number,transaction date,"Total price (10,000 yuan)","Unit price (10,000 yuan/square meter)",Total area(ping),Proportion of main building,House age,management organization,elevator,City,...,Land,Construction,Car,Bedrooms,Living rooms,Bathrooms,Encoded_type,Encoded_floor,Encoded_purpose,Encoded_city
0,土城區中華路一段５７號四樓,104/07/01,820.0,32.2,25.50,100.00%,39.0,0,NaN,New Taipei,...,1,1,0,3,2,2,2,2349,2,0
1,平鎮區湧?路２５巷１５號,104/07/01,218.0,0.0,9.60,NaN,45.0,0,NaN,Taoyuan,...,2,1,0,2,1,1,11,1654,2,3
2,平鎮區金陵路２５８號２F,104/07/01,521.3,17.2,30.38,74.63%,22.0,1,NaN,Taoyuan,...,2,1,0,3,2,2,8,1491,2,3
3,平鎮區平東路３０２巷４號,104/07/01,310.0,0.0,25.05,NaN,36.0,0,NaN,Taoyuan,...,1,1,0,4,3,2,11,1659,2,3
4,平鎮區高雙路４８巷２８號,104/07/01,1100.0,0.0,61.34,NaN,9.0,1,NaN,Taoyuan,...,1,1,0,4,3,3,11,1669,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385743,三芝區田心子１５之１１號四樓,110/07/29,155.0,5.4,28.76,77.46%,26.0,1,0.0,New Taipei,...,2,1,0,3,2,2,2,2395,2,0
385744,八里區龍米路一段２４６號十四樓之１,110/07/29,480.0,23.9,20.10,69.96%,20.0,1,1.0,New Taipei,...,1,1,0,1,1,1,0,2179,2,0
385745,三芝區淺水灣街７之１號八樓,110/07/29,580.0,16.3,35.69,33.14%,24.0,1,1.0,New Taipei,...,1,1,0,2,2,1,8,1742,2,0
385746,三芝區田心子１５之９號三樓,110/07/30,168.0,6.8,24.57,76.45%,26.0,0,0.0,New Taipei,...,2,1,0,3,2,1,2,1107,2,0
385747,八里區文昌一街８號九樓,110/07/31,570.0,24.8,22.99,60.02%,3.0,1,1.0,New Taipei,...,1,1,0,2,1,1,0,1187,2,0

In [ ]:
all_df_split

,Lot location or house number,Community abbreviation,transaction date,"Total price (10,000 yuan)","Unit price (10,000 yuan/square meter)",Total area(ping),Proportion of main building,type,House age,Floor type/floor height,Number of transactions,The current layout of the building,management organization,elevator,The main purpose,Remark,City,geometry_lat,geometry_lng
0,土城區中華路一段５７號四樓,NaN,104/07/01,820.0,32.2,25.50,100.00%,公寓(5樓含以下無電梯),39.0,"四層,陽台/四層",土:1 建:1車:0,3房2廳2衛,無,NaN,住家用,含增建或未登記建物。含增建或未登記建物。;,New Taipei,24.988061,121.445661
1,平鎮區湧?路２５巷１５號,NaN,104/07/01,218.0,0.0,9.60,NaN,透天厝,45.0,全/一層,土:2 建:1車:0,2房1廳1衛,無,NaN,住家用,NaN,Taoyuan,24.929602,121.205396
2,平鎮區金陵路２５８號２F,NaN,104/07/01,521.3,17.2,30.38,74.63%,華廈(10層含以下有電梯),22.0,二層/七層,土:2 建:1車:0,3房2廳2衛,有,NaN,住家用,NaN,Taoyuan,24.944512,121.222069
3,平鎮區平東路３０２巷４號,NaN,104/07/01,310.0,0.0,25.05,NaN,透天厝,36.0,全/二層,土:1 建:1車:0,4房3廳2衛,無,NaN,住家用,含增建或未登記建物。含增建或未登記建物。;,Taoyuan,24.915259,121.247581
4,平鎮區高雙路４８巷２８號,馥園,104/07/01,1100.0,0.0,61.34,NaN,透天厝,9.0,全/四層,土:1 建:1車:0,4房3廳3衛,有,NaN,住家用,NaN,Taoyuan,24.956776,121.190449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385743,三芝區田心子１５之１１號四樓,NaN,110/07/29,155.0,5.4,28.76,77.46%,公寓(5樓含以下無電梯),26.0,四層/五層,土:2 建:1車:0,3房2廳2衛,有,無,住家用,陽台外推;,New Taipei,NaN,NaN
385744,八里區龍米路一段２４６號十四樓之１,麗池海岸,110/07/29,480.0,23.9,20.10,69.96%,住宅大樓(11層含以上有電梯),20.0,十四層/二十一層,土:1 建:1車:0,1房1廳1衛,有,有,住家用,親友、員工、共有人或其他特殊關係間之交易;,New Taipei,NaN,NaN
385745,三芝區淺水灣街７之１號八樓,佛朗明哥B區,110/07/29,580.0,16.3,35.69,33.14%,華廈(10層含以下有電梯),24.0,八層/十層,土:1 建:1車:0,2房2廳1衛,有,有,住家用,其他增建:露台夾層;其他增建;,New Taipei,NaN,NaN
385746,三芝區田心子１５之９號三樓,NaN,110/07/30,168.0,6.8,24.57,76.45%,公寓(5樓含以下無電梯),26.0,三層/五層,土:2 建:1車:0,3房2廳1衛,無,無,住家用,窗框增建。其他增建;,New Taipei,NaN,NaN
385747,八里區文昌一街８號九樓,陽光峇里,110/07/31,570.0,24.8,22.99,60.02%,住宅大樓(11層含以上有電梯),3.0,九層/十四層,土:1 建:1車:0,2房1廳1衛,有,有,住家用,NaN,New Taipei,NaN,NaN